version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  core:
    depends_on:
      - db
    image: syntlabs/vpn_core
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  db_data:
  pg_data:
